[build]
  publish = "packages/.vitepress/dist"
  command = "npm run docs:build"

[[redirects]]
  from = "https://vueuse.js.org/*"
  to = "https://vueuse.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"
  NODE_VERSION = "16"
