[build]
publish = "packages/.vitepress/dist"
command = "pnpm run install-fonts && pnpm run docs:build"

[build.environment]
NODE_OPTIONS = "--max-old-space-size=5120"
NODE_VERSION = "24"

[[redirects]]
from = "https://vueuse.js.org/*"
to = "https://vueuse.org/:splat"
status = 301
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
